<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Robson Bruno Dutra Pereira">

<title>7&nbsp; Metodologia de Superfície de Resposta – Modelagem e Otimização de Experimentos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-fatunrep_frac.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-rsm.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Metodologia de Superfície de Resposta</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Modelagem e Otimização de Experimentos</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefácio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Dists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Distribuições importantes à modelagem e otimização de Experimentos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Testes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Testes de hipóteses para média de uma e duas amostras</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Planejamento totalmente aleatorizado e análise de variância para um fator</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-ANOVA_blocos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Planejamento com blocos completos aleatorizados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-fat2k.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Fatorial de dois níveis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-fatunrep_frac.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Economia na experimentação e busca de região de curvatura via Fatorial 2^k</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-rsm.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Metodologia de Superfície de Resposta</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">7.1</span> Introdução</a></li>
  <li><a href="#intuição" id="toc-intuição" class="nav-link" data-scroll-target="#intuição"><span class="header-section-number">7.2</span> Intuição</a></li>
  <li><a href="#planejamento-composto-central" id="toc-planejamento-composto-central" class="nav-link" data-scroll-target="#planejamento-composto-central"><span class="header-section-number">7.3</span> Planejamento composto central</a></li>
  <li><a href="#estimativa-dos-coeficientes-de-regressão" id="toc-estimativa-dos-coeficientes-de-regressão" class="nav-link" data-scroll-target="#estimativa-dos-coeficientes-de-regressão"><span class="header-section-number">7.4</span> Estimativa dos coeficientes de regressão</a></li>
  <li><a href="#condições-de-otimalidade-de-primeira-ordem" id="toc-condições-de-otimalidade-de-primeira-ordem" class="nav-link" data-scroll-target="#condições-de-otimalidade-de-primeira-ordem"><span class="header-section-number">7.5</span> Condições de otimalidade de primeira ordem</a></li>
  <li><a href="#condições-de-otimalidade-de-segunda-ordem" id="toc-condições-de-otimalidade-de-segunda-ordem" class="nav-link" data-scroll-target="#condições-de-otimalidade-de-segunda-ordem"><span class="header-section-number">7.6</span> Condições de otimalidade de segunda ordem</a></li>
  <li><a href="#planejamento-box-behnken" id="toc-planejamento-box-behnken" class="nav-link" data-scroll-target="#planejamento-box-behnken"><span class="header-section-number">7.7</span> Planejamento Box-Behnken</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Metodologia de Superfície de Resposta</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Robson Bruno Dutra Pereira </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introdução" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="introdução"><span class="header-section-number">7.1</span> Introdução</h2>
<p>A metodologia de superfície de resposta (response surface methodology - RSM) foi apresentada por Box e Wilson (1951) como uma proposta para modelagem e otimização via experimentos planejados, sendo inicialmente aplicada em experimentos químicos. Atualmente a RSM é aplicada em diversas áreas onde deseja-se modelar e otimizar uma determinada resposta <span class="math inline">\(y\)</span> em função de <span class="math inline">\(k\)</span> variáveis de controle <span class="math inline">\(x_1, x_2, \dots, x_k\)</span>. Dentro do contexto do DOE a RSM é um dos métodos mais usados para otimização em engenharia. As variáveis ditas de controle são independentes e podem ser referenciadas na literatura como variáveis preditoras, de controle ou de processo.</p>
<p>Neste capítulo são utilizados os pacotes <code>rsm</code>, <code>ggplot2</code> e <code>ggpubr</code>, além das funções básicas do R. Recomenda-se a instalação destes utilizando o comando <code>install.packages("&lt;nome_pacote&gt;")</code>. Sempre que aparecer nos blocos de código R propostos o comando <code>library(&lt;nome_pacote&gt;)</code> para carregar um determinado pacote, antes este deve ser instalado.</p>
</section>
<section id="intuição" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="intuição"><span class="header-section-number">7.2</span> Intuição</h2>
<p>Considerando uma resposta <span class="math inline">\(y\)</span> dependente dos níveis de <span class="math inline">\(k\)</span> variáveis independentes e quantitativas, passíveis de controle e mensuração, dada a observação de <span class="math inline">\(N\)</span> combinações dos níveis das <span class="math inline">\(k\)</span> variáveis de controle, pode-se estimar um modelo de resposta de <span class="math inline">\(y\)</span> em função de <span class="math inline">\(x_1, ..., x_k\)</span>, conforme segue</p>
<p><span class="math display">\[
y=f(\mathbf{x})+\varepsilon=f\left(x_1, x_2, \ldots, x_k\right)+\varepsilon\text{,}
\]</span></p>
<p>com o erro experimental normalmente distribuído, <span class="math inline">\(\varepsilon \sim N(0,\sigma^2_\varepsilon)\)</span>.</p>
<p>O erro experimental, dada a existência de variáveis de ruído, faz com que o modelo de superfície de resposta seja uma aproximação para a resposta na região experimental <span class="math inline">\(k\)</span> dimensional. A motivação para a aproximação de uma função desconhecida em uma determinada região é baseada na expansão da série de Taylor em torno do ponto <span class="math inline">\(\mathbf{x_0} =x_{10}, x_{20}, ..., x_{k0}\)</span>, <span class="math inline">\(u = 1, ..., N\)</span>. Por exemplo, considerando que uma aproximação de segunda ordem seja razoável para a região de interesse, um modelo de aproximação seria conforme <a href="#eq-taylor" class="quarto-xref">Equação&nbsp;<span>7.1</span></a>.</p>
<p><span id="eq-taylor"><span class="math display">\[
\begin{equation}
\begin{aligned}
f \cong &amp; f\left(x_{10}, x_{20}, \ldots, x_{k0}\right) + \sum_{i=1}^k \left.\frac{\partial f}{\partial x_i}\right|_{\mathbf{x}=\mathbf{x}_0} \left(x_i - x_{i0}\right) \\
&amp; + \frac{1}{2} \sum_{i=1}^k \left.\frac{\partial^2 f}{\partial x_i^2}\right|_{\mathbf{x}=\mathbf{x}_0} \left(x_i - x_{i0}\right)^2 \\
&amp; + \sum_{i &lt; j} \left.\frac{\partial^2 f}{\partial x_i \partial x_j}\right|_{\mathbf{x}=\mathbf{x}_0} \left(x_i - x_{i0}\right)\left(x_j - x_{j0}\right)
\end{aligned}
\end{equation}
\tag{7.1}\]</span></span></p>
<p>Onde: - <span class="math inline">\(\beta_0 = f\left(x_{10}, x_{20}, \ldots, x_{k0}\right)\)</span></p>
<ul>
<li><p><span class="math inline">\(\beta_i = \left.\frac{\partial f}{\partial x_i}\right|_{\mathbf{x}=\mathbf{x}_0}\)</span> (termos lineares)</p></li>
<li><p><span class="math inline">\(\beta_{ii} = \frac{1}{2} \left.\frac{\partial^2 f}{\partial x_i^2}\right|_{\mathbf{x}=\mathbf{x}_0}\)</span> (termos quadráticos puros)</p></li>
<li><p><span class="math inline">\(\beta_{ij} = \left.\frac{\partial^2 f}{\partial x_i \partial x_j}\right|_{\mathbf{x}=\mathbf{x}_0}\)</span> (termos de interação)</p></li>
</ul>
<p>O modelo final, após reparametrização, fica conforme <a href="#eq-rsm" class="quarto-xref">Equação&nbsp;<span>7.2</span></a>. Os termos quadráticos, <span class="math inline">\(\beta_{ii} x_i^2\)</span>, são a novidade em relação ao modelo obtido via fatorial <span class="math inline">\(2^k\)</span>. Este modelo é dito de segunda ordem completo, contendouma constante, <span class="math inline">\(k\)</span> termos lineares, <span class="math inline">\(k\)</span> termos quadráticos ou de segunda ordem puros e <span class="math inline">\(k(k-1)/2\)</span> termos de interação de sgeunda ordem ou termos de segunda ordem mistos.</p>
<p><span id="eq-rsm"><span class="math display">\[
y = \beta_0 + \sum_{i=1}^k \beta_i x_i + \sum_{i=1}^k \beta_{ii} x_i^2 + \sum_{i &lt; j} \beta_{ij} x_i x_j + \varepsilon
\tag{7.2}\]</span></span></p>
<p>O procedimento para encontrar a superfície de resposta pode seguir estratégia sequencial, envolvendo experimentos iniciais de varredura, busca da região de curvatura, estimativa de um modelo de superfície de resposta, até a obtenção das condições ótimas operacionais. Por exemplo, supondo um caso bidimensional com domínio experimental amplo, conforme observado na <a href="#fig-steeps" class="quarto-xref">Figura&nbsp;<span>7.1</span></a>, observa-se em cinza uma suposta função desconhecida de interesse. Para fins de modelagem e otimização, supõe-se inicialmente que o analista selecione a região delimitada pelo quadrado vermelho para um primeiro planejamento fatorial <span class="math inline">\(2^k\)</span> com pontos centrais. A definição de uma região inicial pequena é razoável, visto que uma aproximação quadrática não seria suficiente para uma região ampla e complexa. Obtém-se para esta região um modelo linear. Define-se a direção de máximo crescimento da resposta a partir do gradiente da função linear estimada. Realiza-se outro planejamento fatorial <span class="math inline">\(2^k\)</span> com pontos centrais. Obtém-se outro modelo linear e, analogamente, define-se a direção de máximo crescimento da resposta via gradiente. Finalmente, na terceira região a ser explorada, como o teste de curvatura realizado via fatorial <span class="math inline">\(2^k\)</span> com pontos centrais indicou curvatura significativa, completa-se o planejamento com mais pontos e novos experimentos, definindo um planejamento com região circular observada em azul, viabilizando a obtenção de um modelo quadrático passível de otimização.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-steeps" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-steeps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-rsm_files/figure-html/fig-steeps-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-steeps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.1: Busca de região de curvatura via experimentação sequencial e subida mais íngreme
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="planejamento-composto-central" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="planejamento-composto-central"><span class="header-section-number">7.3</span> Planejamento composto central</h2>
<p>O planejamento composto central (<em>central composite design</em> - CCD) apresenta boas propriedades de variância e tem sido extensivamente usado para obter modelos de superfície de resposta. O CCD possibilita a experimentação sequencial, garantindo economia na experimentação e busca de região de curvatura. Métodos como fatorial fracionado, blocagem do fatorial com pontos centrais e subida mais íngreme, conforme ilustrado na <a href="#fig-steeps" class="quarto-xref">Figura&nbsp;<span>7.1</span></a> são comumente utilizados. Entretanto, em alguns problemas, devido a restrições de região experimental, realizar o CCD de forma direta é suficiente para obtenção de um modelo quadrático definitivo.</p>
<p>A <a href="#fig-ccd" class="quarto-xref">Figura&nbsp;<span>7.2</span></a> ilustra o planejamento CCD para <span class="math inline">\(k = 2\)</span> e <span class="math inline">\(k = 3\)</span> variáveis de controle. Pode-se observar que o planejamento é composto de <span class="math inline">\(2^k\)</span> pontos fatoriais (ou <span class="math inline">\(2^{k-p}\)</span> pontos de um fatorial fracionado com resolução V ou maior de preferência), <span class="math inline">\(2k\)</span> pontos axiais e <span class="math inline">\(nc\)</span> pontos centrais. Este planejamento pode ser usado para obter um modelo na forma da <a href="#eq-rsm" class="quarto-xref">Equação&nbsp;<span>7.2</span></a>. A <a href="#tbl-ccd" class="quarto-xref">Tabela&nbsp;<span>7.1</span></a> apresenta um arranjo CCD genérico. A distância dos pontos axiais <span class="math inline">\(\rho\)</span> e o número de pontos centrais é definida visando propriedades ótimas do planejamento e de previsão.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ccd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ccd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/ccd.png" class="img-fluid figure-img" width="1343">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ccd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.2: Representação do CCD (a) <span class="math inline">\(k=3\)</span>; (b) <span class="math inline">\(k=2\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div id="tbl-ccd" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ccd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;7.1: Planejamento CCD genérico
</figcaption>
<div aria-describedby="tbl-ccd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-bordered do-not-create-environment cell caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">ordem</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">x₁</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">x₂</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">⋯</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">xₖ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">1</td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">-1</td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">-1</td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">-1</td>
</tr>
<tr class="even">
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">1</td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">-1</td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">-1</td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">1</td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">-1</td>
</tr>
<tr class="even">
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">1</td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">1</td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋮</span></td>
</tr>
<tr class="even">
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">n<sub>f</sub> = 2<sup>k</sup></span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">1</td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">1</td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(204, 239, 250, 255) !important;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">1</td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">-ρ</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
</tr>
<tr class="even">
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">ρ</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">-ρ</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
</tr>
<tr class="even">
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">ρ</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋮</span></td>
</tr>
<tr class="even">
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">-ρ</span></td>
</tr>
<tr class="odd">
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">n<sub>a</sub> = 2k</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(230, 247, 179, 255) !important;"><span class="math">ρ</span></td>
</tr>
<tr class="even">
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;">1</td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;"><span class="math">⋮</span></td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;"><span class="math">⋮</span></td>
</tr>
<tr class="even">
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;"><span class="math">n<sub>c</sub></span></td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;">0</td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;"><span class="math">⋯</span></td>
<td style="text-align: center; background-color: rgba(255, 214, 214, 255) !important;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Pelas ilustrações da <a href="#fig-ccd" class="quarto-xref">Figura&nbsp;<span>7.2</span></a>, pode-se inferir que o CCD se limita a uma região experimental esférica. O valor do raio do planejamento, <span class="math inline">\(\rho\)</span>, pode ser considerado igual a <span class="math inline">\(\sqrt{k}\)</span> para que esta região seja um círculo, esfera ou hiperesfera perfeita. No entanto, Box definiu que o ideal para obter um CCD dito rotacionável é que <span class="math inline">\(\rho = 2^{k/4}\)</span>. Um CCD rotacionável seria aquele no qual a variância do modelo se mantenha constante em pontos equidistanciados do centro do planejamento ou, de forma análoga, que a variância e covariância dos efeitos não seja alterada pela rotação do planejamento ou modelo. A rotação às vezes é importante, por exemplo ao diagonalizar o modelo para verificar as condições de otimalidade de primeira ordem, ou caracterizar a superfície de resposta. A título de exemplo a seguir expõe-se o código para obtenção de um CCD para <span class="math inline">\(k = 3\)</span>. Observa-se que <span class="math inline">\(\rho = 2^{k/4} = 1,6818\)</span>. É possível obter um CCD esférico fazendo <code>alpha = "spherical"</code>. Nos casos quando o número de fatores <span class="math inline">\(k\)</span> é par o CCD rotacionável é perfeitamente esférico. Em casos onde a região experimental é restrita e deseja-se que a distância dos pontos axiais não seja maior que a dos fatoriais, faz-se <code>alpha = "faces"</code>, obtendo um CCD de face centrada (<em>face-centered central composite design</em> - FCD). O CCD permite a blocagem da sequência experimental, caso inicalmente seja realizado o fatorial compontos centrais, conforme observado na última coluna. Porém, é necessário que sejam alocados pontos centrais na parte fatorial com o argumento <code>n0</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsm)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ccd</span>(<span class="dv">3</span>, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n0 =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">3</span>), </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="st">"rotatable"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">randomize =</span> F</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   run.order std.order  x1.as.is  x2.as.is  x3.as.is Block
1          1         1 -1.000000 -1.000000 -1.000000     1
2          2         2  1.000000 -1.000000 -1.000000     1
3          3         3 -1.000000  1.000000 -1.000000     1
4          4         4  1.000000  1.000000 -1.000000     1
5          5         5 -1.000000 -1.000000  1.000000     1
6          6         6  1.000000 -1.000000  1.000000     1
7          7         7 -1.000000  1.000000  1.000000     1
8          8         8  1.000000  1.000000  1.000000     1
9          1         1 -1.681793  0.000000  0.000000     2
10         2         2  1.681793  0.000000  0.000000     2
11         3         3  0.000000 -1.681793  0.000000     2
12         4         4  0.000000  1.681793  0.000000     2
13         5         5  0.000000  0.000000 -1.681793     2
14         6         6  0.000000  0.000000  1.681793     2
15         7         7  0.000000  0.000000  0.000000     2
16         8         8  0.000000  0.000000  0.000000     2
17         9         9  0.000000  0.000000  0.000000     2

Data are stored in coded form using these coding formulas ...
x1 ~ x1.as.is
x2 ~ x2.as.is
x3 ~ x3.as.is</code></pre>
</div>
</div>
<p>No CCD os pontos fatoriais ou fracionados são usados para estimar os efeitos lineares e interações de segunda ordem. Os pontos centrais ajudam a estimar o erro experimental e contribuem para estimar os termos quadráticos. Os pontos axiais tem grande contribuição na estimativa dos termos quadráticos, de forma que sem eles somente o somatório dos termos quadráticos, <span class="math inline">\(\sum \beta_{ii}\)</span>, seria obtido, o que é usado para testar curvatura.</p>
<p>Nos planejamentos fatoriais a ortogonalidade do planejamento é uma propriedade que garante independência das variáveis de controle, baixa variância dos coeficientes, independência dos coeficientes e boa capacidade de previsão do modelo de resposta. Entretanto, em planejamentos de segunda ordem a ortogonalidade não é uma propriedade presente de forma a garantir a total independência dos coeficientes de regressão.</p>
<div id="exm-fatunrep1" class="theorem example">
<p><span class="theorem-title"><strong>Exemplo 7.1</strong></span> Seja um experimento para determinar o conteúdo de cobre em diferentes amostras de água via espectrometria de emissão óptica. Os fatores de controle são x1: <span class="math inline">\(pH\)</span> e x2: vazao - <span class="math inline">\(vz\)</span> (<span class="math inline">\(mL/min\)</span>). Os níveis fatoriais são 7 e 9 para pH e 7 e 9 <span class="math inline">\(mL/min\)</span> para <span class="math inline">\(vz\)</span>. A resposta consiste no sinal analítico resultante das medições de altura de pico instrumental. Uma vez medidos tais valores para os experimentos realizados, o maior foi considerado como 100 e os demais como porcentagem deste máximo (sinal analítico relativo). Foi utilizado um CCD rotacionável e RSM para inferência, modelagem e otimização. https://doi.org/10.1016/j.jhazmat.2010.07.014</p>
</div>
<p>A <a href="#tbl-ccdpico" class="quarto-xref">Tabela&nbsp;<span>7.2</span></a> apresenta o planejamento considerado já com os resultados da resposta. O código apresentado em sequência pode ser usado para obtenção deste CCD e armazenamento da resposta. Pode-se observar que os fatores podem ser definidos de forma decodificada, ou seja, nas unidades originais. Por exemplo <span class="math inline">\(x_1\)</span> consiste na vazão codificada, isto é, <span class="math inline">\(x_1 = (vz-8)/1\)</span>, onde 8 seria o nível central da vazão (a média dos fatoriais) e o denominador, neste caso unitário, consiste na distância entre os pontos fatoriais e o central.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Planejamento CCD</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>ccd1 <span class="ot">&lt;-</span> <span class="fu">ccd</span>(<span class="at">basis =</span> <span class="sc">~</span>x1<span class="sc">+</span>x2,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">n0 =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">3</span>),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">alpha =</span> <span class="st">"rotatable"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">randomize =</span> <span class="cn">FALSE</span>, </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">oneblock=</span><span class="cn">TRUE</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">coding =</span> <span class="fu">list</span>(x1 <span class="sc">~</span> (vz <span class="sc">-</span> <span class="dv">8</span>)<span class="sc">/</span><span class="dv">1</span>,  <span class="co"># mL/min</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                          x2 <span class="sc">~</span> (pH <span class="sc">-</span> <span class="dv">8</span>)<span class="sc">/</span><span class="dv">1</span>)) <span class="co"># -</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># resposta - sinal analitico relativo</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">68.64</span>, <span class="fl">69.82</span>, <span class="fl">81.66</span>, <span class="fl">85.80</span>, </span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>       <span class="fl">79.29</span>, <span class="fl">87.57</span>, <span class="fl">74.56</span>, <span class="fl">94.08</span>, </span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>       <span class="dv">100</span>, <span class="fl">99.41</span>, <span class="dv">100</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># adicionando resposta ao planejamento</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>ccd1<span class="sc">$</span>y <span class="ot">&lt;-</span> y</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div id="tbl-ccdpico" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ccdpico-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;7.2: Planejamento CCD para determinação de conteúdo de cobre em água
</figcaption>
<div aria-describedby="tbl-ccdpico-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">run.order</th>
<th style="text-align: right;">std.order</th>
<th style="text-align: right;">vz</th>
<th style="text-align: right;">pH</th>
<th style="text-align: right;">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7.000000</td>
<td style="text-align: right;">7.000000</td>
<td style="text-align: right;">68.64</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">9.000000</td>
<td style="text-align: right;">7.000000</td>
<td style="text-align: right;">69.82</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7.000000</td>
<td style="text-align: right;">9.000000</td>
<td style="text-align: right;">81.66</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">9.000000</td>
<td style="text-align: right;">9.000000</td>
<td style="text-align: right;">85.80</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.585786</td>
<td style="text-align: right;">8.000000</td>
<td style="text-align: right;">79.29</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">9.414214</td>
<td style="text-align: right;">8.000000</td>
<td style="text-align: right;">87.57</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8.000000</td>
<td style="text-align: right;">6.585786</td>
<td style="text-align: right;">74.56</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8.000000</td>
<td style="text-align: right;">9.414214</td>
<td style="text-align: right;">94.08</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8.000000</td>
<td style="text-align: right;">8.000000</td>
<td style="text-align: right;">100.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">8.000000</td>
<td style="text-align: right;">8.000000</td>
<td style="text-align: right;">99.41</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8.000000</td>
<td style="text-align: right;">8.000000</td>
<td style="text-align: right;">100.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="estimativa-dos-coeficientes-de-regressão" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="estimativa-dos-coeficientes-de-regressão"><span class="header-section-number">7.4</span> Estimativa dos coeficientes de regressão</h2>
<p>Seja o modelo da <a href="#eq-rsm" class="quarto-xref">Equação&nbsp;<span>7.2</span></a> escrito de forma expandida conforme <a href="#eq-rsm1" class="quarto-xref">Equação&nbsp;<span>7.3</span></a>.</p>
<p><span id="eq-rsm1"><span class="math display">\[
y=\beta_0+\beta_1 x_1+\ldots+\beta_k x_k+\beta_{11} x_1^2+\ldots+\beta_{k k} x_k^2+\beta_{12} x_1 x_2+\ldots+\beta_{(k-1)(k)} x_{(k-1)} x_{(k)}+\varepsilon
\tag{7.3}\]</span></span></p>
<p>Em notação matricial, para facilitar a obtenção das estimativas de mínimos quadrados para os coeficientes, o modelo na forma da <a href="#eq-rsm" class="quarto-xref">Equação&nbsp;<span>7.2</span></a> e da <a href="#eq-rsm1" class="quarto-xref">Equação&nbsp;<span>7.3</span></a>, de forma análoga ao modelo obtido va fatorial <span class="math inline">\(2^k\)</span>, também pode ser representado como <span class="math inline">\(\mathbf{y}=X \boldsymbol{\beta}+\boldsymbol{\varepsilon}\)</span>, com os devidos ajustes nas matrizes e vetores:</p>
<p><span class="math display">\[
\begin{aligned}
&amp; \mathbf{y}=\left[\begin{array}{c}
y_1 \\
y_2 \\
\vdots \\
y_N
\end{array}\right] ; \quad \mathbf{X}=\left[\begin{array}{cccccccccc}
1 &amp; x_{1(-)} &amp; \cdots &amp; x_{k(-)} &amp; x_1^2 &amp; \cdots &amp; x_k^2 &amp; x_{1(-)} x_{2(-)} &amp; \cdots &amp; x_{k-1(-)} x_{k(-)} \\
1 &amp; x_{1(+)} &amp; \cdots &amp; x_{k(-)} &amp; x_1^2 &amp; \cdots &amp; x_k^2 &amp; x_{1(+)} x_{2(-)} &amp; \cdots &amp; x_{k-1(-)} x_{k(-)} \\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
1 &amp; x_{1(+)} &amp; \cdots &amp; x_{k(+)} &amp; x_1^2 &amp; \cdots &amp; x_k^2 &amp; x_{1(+)} x_{2(+)} &amp; \cdots &amp; x_{k-1(-)} x_{k(-)}
\end{array}\right] ; \\
&amp; \boldsymbol{\beta}=\left[\begin{array}{c}
\beta_0 \\
\beta_1 \\
\vdots \\
\beta_k \\
\beta_{11} \\
\vdots \\
\beta_{k k} \\
\beta_{12} \\
\vdots \\
\beta_{(k-1)(k)}
\end{array}\right]; \text{ }
\boldsymbol{\varepsilon}=\left[\begin{array}{c}
\varepsilon_1 \\
\varepsilon_2 \\
\vdots \\
\varepsilon_N
\end{array}\right]
\end{aligned}.
\]</span></p>
<p>Onde o vetor de respostas <span class="math inline">\(\mathbf y\)</span> é da ordem <span class="math inline">\(N \times 1\)</span>, a matriz do planejamento <span class="math inline">\(\mathbf{X}\)</span> é da ordem <span class="math inline">\(N \times r\)</span>, o vetor de coeficientes <span class="math inline">\(\boldsymbol{\beta}\)</span> é da ordem <span class="math inline">\(r \times 1\)</span> e o vetor do erro aleatório é da ordem <span class="math inline">\(N \times 1\)</span>, sendo <span class="math inline">\(N = 2^k + 2k + n_c\)</span> e <span class="math inline">\(r = 1 + 2^k + 2k + k(k − 1)/2\)</span> para um modelo de resposta completo correspondente à <a href="#eq-rsm1" class="quarto-xref">Equação&nbsp;<span>7.3</span></a>. Os coeficientes podem ser estimados pelo método dos mínimos quadrados, <span class="math inline">\(\hat{\boldsymbol{\beta}}=\left(\mathbf{X}^{\mathbf{T}} \mathbf{X}\right)^{-1} \mathbf{X}^{\mathbf{T}} \mathbf{y}\)</span>. A variância do modelo de superfície de resposta depende da matriz do planejamento <span class="math inline">\(\mathbf X\)</span>, com covariância <span class="math inline">\(\left(\mathbf{X}^{\mathbf{T}} \mathbf{X}\right)^{-1}\)</span>, do ponto avaliado, que em um modelo quadrático completo é da forma <span class="math inline">\(\mathbf x_0^T = [1, x_1, \dots,x_k, x_{11}, \dots,x_{kk}, x_1x_2, \dots, x_{k-1}x_k]^T\)</span>, e do erro experimental <span class="math inline">\(\hat\sigma^2 = \sqrt{MS_E}\)</span>, isto é, <span class="math inline">\(Var[\hat {\mathbf y}(\mathbf x)]=\mathbf x_0^T\left(\mathbf{X}^{\mathbf{T}} \mathbf{X}\right)^{-1}\mathbf x_0\)</span>.</p>
<p>Considerando o exemplo <a href="#exm-fatunrep1" class="quarto-xref">Exemplo&nbsp;<span>7.1</span></a> a seguir expõe-se a sintaxe para obtenção do modelo de regressão de superfície de resposta. Pode-se observar que o comando <code>lm</code> é utilizado, assim como no fatorial <span class="math inline">\(2^k\)</span>. Os termos quadráticos são adicionados usando a sintaxe <code>I(xj^2)</code>. Para o estudo em questão observa-se que o termo linear do pH, o termo quadrático tanto da vazão quanto do pH foram significativos, além da constante.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> (x1<span class="sc">+</span>x2)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">I</span>(x1<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(x2<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> ccd1)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ (x1 + x2)^2 + I(x1^2) + I(x2^2), data = ccd1)

Residuals:
      1       2       3       4       5       6       7       8       9      10 
-3.0731 -4.6705 -2.7245 -4.3219  2.5680  4.8270  3.9440  3.4510  0.1967 -0.3933 
     11 
 0.1967 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   99.803      2.768  36.052 3.09e-07 ***
x1             2.129      1.695   1.256  0.26470    
x2             7.076      1.695   4.174  0.00871 ** 
I(x1^2)      -10.035      2.018  -4.974  0.00420 ** 
I(x2^2)       -9.590      2.018  -4.753  0.00509 ** 
x1:x2          0.740      2.397   0.309  0.77002    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.795 on 5 degrees of freedom
Multiple R-squared:  0.9176,    Adjusted R-squared:  0.8352 
F-statistic: 11.14 on 5 and 5 DF,  p-value: 0.009668</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(aov(lm1))</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>O modelo pode ser reduzido, usando o comando <code>step</code>, conforme segue. É importante notar que a estrutura hierárquica se mantém, de forma que a avaliação da eliminação de um termo linear só será realizada durante o algoritmo de eliminação caso o termo quadrático e os de interação que o involvem forem eliminados antes. Observa-se que o ajuste do modelo passou de 0,8352 para 0,8601 após a redução.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>lm1_red <span class="ot">&lt;-</span> <span class="fu">step</span>(lm1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=37.81
y ~ (x1 + x2)^2 + I(x1^2) + I(x2^2)

          Df Sum of Sq    RSS    AIC
- x1:x2    1      2.19 117.14 36.020
&lt;none&gt;                 114.95 37.813
- I(x2^2)  1    519.39 634.35 54.602
- I(x1^2)  1    568.71 683.66 55.425

Step:  AIC=36.02
y ~ x1 + x2 + I(x1^2) + I(x2^2)

          Df Sum of Sq    RSS    AIC
&lt;none&gt;                 117.14 36.020
- x1       1     36.25 153.39 36.986
- x2       1    400.52 517.66 50.366
- I(x2^2)  1    519.39 636.54 52.640
- I(x1^2)  1    568.71 685.85 53.460</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1_red)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2 + I(x1^2) + I(x2^2), data = ccd1)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.4105 -2.8988  0.1967  3.0095  4.8270 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   99.803      2.551  39.122 1.86e-08 ***
x1             2.129      1.562   1.363  0.22192    
x2             7.076      1.562   4.529  0.00398 ** 
I(x1^2)      -10.035      1.859  -5.397  0.00167 ** 
I(x2^2)       -9.590      1.859  -5.158  0.00210 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.419 on 6 degrees of freedom
Multiple R-squared:  0.916, Adjusted R-squared:  0.8601 
F-statistic: 16.36 on 4 and 6 DF,  p-value: 0.002219</code></pre>
</div>
</div>
</section>
<section id="condições-de-otimalidade-de-primeira-ordem" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="condições-de-otimalidade-de-primeira-ordem"><span class="header-section-number">7.5</span> Condições de otimalidade de primeira ordem</h2>
<p>Após apresentação do planejamento composto central e suas propriedades, além da obtenção do modelo de regressão, convém expor uma forma analítica para possibilitar a avaliação das condições de otimalidade de primeira ordem ou obtenção do ponto estacionário. O modelo exposto na <a href="#eq-rsm1" class="quarto-xref">Equação&nbsp;<span>7.3</span></a> também pode ser exposto em outra notação, sendo esta útil para otimização, conforme <a href="#eq-rsm2" class="quarto-xref">Equação&nbsp;<span>7.4</span></a>:</p>
<p><span id="eq-rsm2"><span class="math display">\[
\hat y = \beta_0 + \mathbf{x}^T\mathbf b + \mathbf{x}^T\mathbf B \mathbf x\text{ ,}
\tag{7.4}\]</span></span></p>
<p>onde <span class="math inline">\(\beta_0\)</span> é a estimativa da constante, <span class="math inline">\(\mathbf{x}\)</span> é o vetor das <span class="math inline">\(k\)</span> variáveis de controle de ordem <span class="math inline">\(k \times 1\)</span>, <span class="math inline">\(\mathbf b\)</span> é o vetor de coeficientes lineares de ordem <span class="math inline">\(k \times 1\)</span> e <span class="math inline">\(\mathbf B\)</span> é a matriz simétrica que contém os termos quadráticos e de interação de ordem <span class="math inline">\(k \times k\)</span>, conforme segue. Pode-se averiguar que os elementos da diagonal principal desta matriz são responsáveis pelos efeitos quadráticos, enquanto os outros elementos contribuem para a obtenção dos termos de interação.</p>
<p><span class="math display">\[
\mathbf b = \left[\begin{array}{c}
\beta_1 \\
\beta_2 \\
\vdots \\
\beta_k
\end{array}\right]\text{, }
\mathbf x = \left[\begin{array}{c}
x_1 \\
x_2 \\
\vdots \\
x_k
\end{array}\right]\text{, }
\mathbf{X} = \left[\begin{array}{cccc}
\beta_{11} &amp; \beta_{12}/2 &amp; \cdots &amp; \beta_{1k}/2 \\
&amp; \beta_{22} &amp; \cdots &amp; \beta_{2k}/2 \\
&amp;  &amp; \ddots &amp; \vdots \\
\text{sym} &amp;   &amp;   &amp; \beta_{kk}
\end{array}\right] \\
\]</span></p>
<p>Para obter o ponto de inflexão ou estacionário, que são as condições de otimalidade de primeira ordem, iguala-se o gradiente da função a zero e resolve-se para <span class="math inline">\(\mathbf x\)</span>, conforme <a href="#eq-xs" class="quarto-xref">Equação&nbsp;<span>7.5</span></a>.</p>
<p><span class="math display">\[
\begin{align}
\nabla \hat y &amp;= \frac {\partial \hat y}{\partial \mathbf x} = 0 \\
&amp;= \mathbf b + 2 \mathbf B \mathbf x = 0 \\
\end{align}
\]</span></p>
<p><span id="eq-xs"><span class="math display">\[
\mathbf x_s = -\frac{1}{2}\mathbf B^{-1}\mathbf b
\tag{7.5}\]</span></span></p>
<p>O pacote <code>rsm</code> apresenta uma saída completa que, além do modelo de superfície de resposta, teste t e ANOVA reduzida, apresenta as condições de otimalidade de primeira ordem, ou ponto estacionário codificado e decodificado, além das condições de otimalidade de segunda ordem, às quais serão explicitadas em sequência. Pode-se usar a seguinte sintaxe, onde o modelo quadrático completo seria obtido via <code>SO(x1,x2,...)</code>. O modelo reduzido deve ser escrito com termos de ordem distinta separados, com os termos de primeira ordem dentro de <code>FO(x1,x2,...)</code> e os termos quadráticos puros em <code>PQ(x1,x2,...)</code>. Caso haja algum termo de interação significativo deveria vir com a sintaxe <code>TWI(xi,xj)</code>. É importante esclarecer que para aplicar o comando <code>step</code> recomenda-se escrever o modelo da forma convencional e usar o comando <code>lm</code>, para depois definir o modelo reduzido análogo via <code>rsm</code>, obtendo uma análise completa.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># modelo completo via funcao rsm</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># rsm1 &lt;- rsm(y~SO(x1,x2), data = ccd1)</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(rsm1)</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># modelo reduzido</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>rsm2 <span class="ot">&lt;-</span> <span class="fu">rsm</span>(y<span class="sc">~</span><span class="fu">FO</span>(x1,x2)<span class="sc">+</span><span class="fu">PQ</span>(x1,x2), <span class="at">data =</span> ccd1)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rsm2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
rsm(formula = y ~ FO(x1, x2) + PQ(x1, x2), data = ccd1)

            Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept)  99.8033     2.5510 39.1225 1.863e-08 ***
x1            2.1287     1.5622  1.3626  0.221920    
x2            7.0757     1.5622  4.5293  0.003978 ** 
x1^2        -10.0354     1.8594 -5.3972  0.001668 ** 
x2^2         -9.5904     1.8594 -5.1579  0.002099 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Multiple R-squared:  0.916, Adjusted R-squared:  0.8601 
F-statistic: 16.36 on 4 and 6 DF,  p-value: 0.002219

Analysis of Variance Table

Response: y
            Df Sum Sq Mean Sq F value   Pr(&gt;F)
FO(x1, x2)   2 436.77  218.39  11.186 0.009458
PQ(x1, x2)   2 841.17  420.59  21.543 0.001826
Residuals    6 117.14   19.52                 
Lack of fit  4 116.91   29.23 251.887 0.003958
Pure error   2   0.23    0.12                 

Stationary point of response surface:
       x1        x2 
0.1060599 0.3688933 

Stationary point in original units:
      vz       pH 
8.106060 8.368893 

Eigenanalysis:
eigen() decomposition
$values
[1]  -9.590417 -10.035417

$vectors
   [,1] [,2]
x1    0   -1
x2   -1    0</code></pre>
</div>
</div>
<p>O ponto estacionário nas unidades originais consiste em vz = 8.106 <span class="math inline">\(mL/min\)</span> e pH = 8.369. O comando <code>rsm</code> também retorna como saídas as matrizes <span class="math inline">\(\mathbf b\)</span> e <span class="math inline">\(\mathbf B\)</span>, viabilizando a obtenção do ponto estacionário como <code>-0.5*solve(B)%*%b</code>, ou usando o comando <code>canonical</code> e a saída <code>xs</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># matrizes b e B</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> rsm2<span class="sc">$</span>b</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> rsm2<span class="sc">$</span>B</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># ponto estacionario</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">canonical</span>(rsm2)<span class="sc">$</span>xs</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># ou</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.5</span><span class="sc">*</span><span class="fu">solve</span>(B)<span class="sc">%*%</span>b</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>xs</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        [,1]
x1 0.1060599
x2 0.3688933</code></pre>
</div>
</div>
<p>Para saber o valor da resposta no ponto estacionário, isto é, <span class="math inline">\(\hat y(\mathbf x_s)\)</span>, pode-se usar o comando <code>predict</code>, conforme segue.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(rsm2, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> xs[<span class="dv">1</span>],</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">x2 =</span> xs[<span class="dv">2</span>]))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
101.2213 </code></pre>
</div>
</div>
<p>O modelo de superfície de resposta pode ser visualizado usando gráficos de superfície e/ou contorno, conforme <a href="#fig-contour1" class="quarto-xref">Figura&nbsp;<span>7.3</span></a> e <a href="#fig-surf1" class="quarto-xref">Figura&nbsp;<span>7.4</span></a>, respectivamente. Especialmente no caso do gráfico de contorno fica fácil confirmar os níveis do ponto estacionário.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contour</span>(rsm2, <span class="sc">~</span>x1 <span class="sc">+</span> x2, <span class="at">image =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-contour1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-contour1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-rsm_files/figure-html/fig-contour1-1.png" class="img-fluid figure-img" width="432">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-contour1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.3: Gráfico de contorno para o experimento de determinação de conteúdo de cobre em água
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">persp</span>(rsm2, <span class="sc">~</span>x1 <span class="sc">+</span> x2, <span class="at">zlab=</span><span class="st">"y [%]"</span>, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">50</span>), <span class="at">contours =</span> (<span class="st">"colors"</span>))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-surf1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-surf1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-rsm_files/figure-html/fig-surf1-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-surf1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.4: Gráfico de superfície para o experimento de determinação de conteúdo de cobre em água
</figcaption>
</figure>
</div>
</div>
</div>
<p>Outras visualizações podem ser concebidas para interpretar o efeito dos fatores na resposta de interesse, conforme <a href="#fig-effectsplot" class="quarto-xref">Figura&nbsp;<span>7.5</span></a> e <a href="#fig-interplot" class="quarto-xref">Figura&nbsp;<span>7.6</span></a> com códigos explicitados à seguir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># x1</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>x1_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(ccd1<span class="sc">$</span>x1), <span class="fu">max</span>(ccd1<span class="sc">$</span>x1), <span class="fl">0.1</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>center_grid <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="fu">length</span>(x1_grid))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>x_range <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">min</span>(<span class="fu">c</span>(<span class="fu">predict</span>(rsm2,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>                             <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> x1_grid, </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>                                                  <span class="at">x2 =</span> center_grid)),</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">predict</span>(rsm2,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>                             <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x2 =</span> x1_grid, </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>                                                  <span class="at">x1 =</span> center_grid)))),</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>             <span class="fu">max</span>(<span class="fu">c</span>(<span class="fu">predict</span>(rsm2,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>                             <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> x1_grid, </span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>                                                  <span class="at">x2 =</span> center_grid)),</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">predict</span>(rsm2,</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>                             <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x2 =</span> x1_grid, </span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>                                                  <span class="at">x1 =</span> center_grid))))</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>             )</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span>        </span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> x1_grid, </span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> (<span class="fu">predict</span>(rsm2,</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>                             <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> x1_grid, </span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>                                                  <span class="at">x2 =</span> center_grid)))),</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">colour =</span> <span class="st">'firebrick1'</span>) <span class="sc">+</span></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"vz [mL/min]"</span>) <span class="sc">+</span></span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"sinal [%]"</span>) <span class="sc">+</span> </span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(x_range) <span class="sc">+</span> </span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="at">label =</span> <span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>)) <span class="sc">+</span></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span>        </span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> x1_grid, </span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> (<span class="fu">predict</span>(rsm2,</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a>                             <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x2 =</span> x1_grid, </span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a>                                                  <span class="at">x1 =</span> center_grid)))),</span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a>            <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a>            <span class="at">colour =</span> <span class="st">'dodgerblue3'</span>) <span class="sc">+</span></span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"pH"</span>) <span class="sc">+</span></span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"sinal [%]"</span>) <span class="sc">+</span> </span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(x_range) <span class="sc">+</span> </span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="at">label =</span> <span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>)) <span class="sc">+</span></span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(p1,p2, <span class="at">nrow=</span><span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-effectsplot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-effectsplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-rsm_files/figure-html/fig-effectsplot-1.png" class="img-fluid figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-effectsplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.5: Gráficos de efeitos principais para o experimento de determinação de conteúdo de cobre em água
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>p12 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> x1_grid, </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> <span class="fu">predict</span>(rsm2, </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x2 =</span> x1_grid, </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                                                 <span class="at">x1 =</span> center_grid)),</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">"8"</span>, <span class="at">linetype =</span> <span class="st">"8"</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">''</span>) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'pH'</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">'sinal [%]'</span>) <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">58</span>,<span class="dv">103</span>) <span class="sc">+</span> </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="at">label =</span> <span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>)) <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>x2_grid_1 <span class="ot">=</span> <span class="fu">rep</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="fu">length</span>(x1_grid))</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>x2_grid1 <span class="ot">=</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="fu">length</span>(x1_grid))</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>p12 <span class="ot">&lt;-</span> p12 <span class="sc">+</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> x1_grid,</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> <span class="fu">predict</span>(rsm2,</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>                            <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x2 =</span> x1_grid,</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>                                                 <span class="at">x1 =</span> x2_grid_1)),</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">"7"</span>, <span class="at">linetype =</span> <span class="st">"7"</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> x1_grid, </span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> <span class="fu">predict</span>(rsm2, </span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>                            <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x2 =</span> x1_grid, </span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>                                                 <span class="at">x1 =</span> x2_grid1)),</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">"9"</span>, <span class="at">linetype =</span> <span class="st">"9"</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">"vz"</span>, </span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>                     <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"7"</span> <span class="ot">=</span> <span class="st">"orange1"</span>, </span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"8"</span> <span class="ot">=</span> <span class="st">"green3"</span>, </span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"9"</span> <span class="ot">=</span> <span class="st">"red1"</span>)) <span class="sc">+</span></span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype_manual</span>(<span class="at">name =</span> <span class="st">"vz"</span>, </span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>                     <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"7"</span> <span class="ot">=</span> <span class="st">"dashed"</span>, </span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"8"</span> <span class="ot">=</span> <span class="st">"longdash"</span>, </span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"9"</span> <span class="ot">=</span> <span class="st">"solid"</span>))</span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a>p12</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-interplot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-interplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-rsm_files/figure-html/fig-interplot-1.png" class="img-fluid figure-img" width="336">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.6: Gráfico de interação para o experimento de determinação de conteúdo de cobre em água
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="condições-de-otimalidade-de-segunda-ordem" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="condições-de-otimalidade-de-segunda-ordem"><span class="header-section-number">7.6</span> Condições de otimalidade de segunda ordem</h2>
<p>Por ambas representações gráficas das <a href="#fig-effectsplot" class="quarto-xref">Figura&nbsp;<span>7.5</span></a> e <a href="#fig-interplot" class="quarto-xref">Figura&nbsp;<span>7.6</span></a> observa-se que o modelo obtido tem convexidade para baixo, apresentando ponto de máximo. Como neste experimento deseja-se maximizar a resposta, o ponto estacionário é suficiente para garantir o máximo rendimento no processo de estração de cobre. Existem casos, porém, que não é possível avaliar se o ponto estacionário é de interesse prático ou seja, sua natureza, de forma a saber se ele maximiza ou minimiza a função. Isso acontece porque quando <span class="math inline">\(k \ge 3\)</span> a superfície de resposta não pode ser visualizada. Em tais casos é comum avaliar as condições de otimalidade de segunda ordem ou a natureza do ponto estacionário e a convexidade da superfície de resposta.</p>
</section>
<section id="planejamento-box-behnken" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="planejamento-box-behnken"><span class="header-section-number">7.7</span> Planejamento Box-Behnken</h2>
<p>Xxx</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-fatunrep_frac.html" class="pagination-link" aria-label="Economia na experimentação e busca de região de curvatura via Fatorial 2^k">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Economia na experimentação e busca de região de curvatura via Fatorial 2^k</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>